stages:
  - build
  - test

build:ubuntu-x86_64:
  stage: build
  image: amd64/ubuntu
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update && apt-get install -y build-essential libtool pkg-config libgtk-3-dev
    - make

  build:ubuntu-x86:
  stage: build
  image: i386/ubuntu
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update && apt-get install -y build-essential libtool pkg-config libgtk-3-dev
    - make
  
build:ubuntu-arm64v8:
  stage: build
  image: arm64v8/ubuntu
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update && apt-get install -y build-essential libtool pkg-config libgtk-3-dev
    - make

build:ubuntu-arm32v7:
  stage: build
  image: arm32v7/ubuntu
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update && apt-get install -y build-essential libtool pkg-config libgtk-3-dev
    - make

build:raspbian:
  stage: build
  image: raspbian/stretch
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update && apt-get install -y build-essential libtool pkg-config libgtk-3-dev
    - make

test:
  stage: test
  script:
  - echo "TEST"