stages:
  - build
  - test

build:ubuntu x86_64:
  stage: build
  image: ubuntu:latest
  script:    
    - apt-get update && apt-get install -y build-essential libtool pkg-config libgtk-3-dev && DEBIAN_FRONTEND=noninteractive 
    - make
  
build:ubuntu arm64:
  stage: build
  image: arm64v8/ubuntu:latest
  script:
    - apt-get update && apt-get install -y build-essential libtool pkg-config libgtk-3-dev
    - make

build:ubuntu arm32:
  stage: build
  image: arm32v7/ubuntu:latest
  script:
    - apt-get update && apt-get install -y build-essential libtool pkg-config libgtk-3-dev
    - make

build:raspbian:
  stage: build
  image: raspbian/stretch
  script:
    - apt-get update && apt-get install -y build-essential libtool pkg-config libgtk-3-dev
    - make

test:
  stage: test
  script:
  - echo "TEST"